name: parking_area_owner_app
description: A Flutter app for parking area owners
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  intl: ^0.18.1
  lottie: ^3.1.2
  razorpay_flutter: ^1.3.0
  js: ^0.7.0 # Add this line
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/success.json
    - assets/lottie/main_car.json
